### ISSUE TITLE
feature: DBC parser

### ISSUE THREAD

**Issue by claudiiolima** [Tbruno25/can-explorer#10]
It would be nice to add a DBC file to parse data not only in messages, but in signal too.

**Comment by Tbruno25** [comment]
I'm definitely open to including support for dbc files if it adds value or fills a gap that other tooling doesn't implement. However, I'm not quite sure I understand the use case you're describing. Could you please provide further details or an example of what you envision?

**Comment by Tbruno25** [comment]
Closing this but feel free to re-open!
