### ISSUE TITLE
support: How to Launch Viewer with vcan?

### ISSUE THREAD

**Issue by JR-SRUSA** [Tbruno25/can-explorer#12]
Hi, I found your medium article explaining can-explorer (FKA canopy?). I have CAN data coming in on vcan0 after following the directions at ICSim. I am able to view with both `candump` and `cansniffer`, but I can't figure out how to get your live plotter working. I can launch it using `$ can-explorer`, but how do I configure the GUI settings for vcan0? 

Sorry for the newb question, I'm looking through your docs but its not apparent to me, as your docs are mostly for the Python scripting interface, and don't mention ICSim/ vcan0. 

Thanks for your help, really great code!

**Comment by JR-SRUSA** [comment]
For anyone else wondering the same, look at this gif, it explains how to start it up: https://github.com/Tbruno25/can-explorer/docs/images/demo.gif

**Comment by Tbruno25** [comment]
Thanks for taking the time to check out the article and glad you got it figured out! :+1:

**Comment by JR-SRUSA** [comment]
@Tbruno25 Thanks for taking the time to make the software and the article, it's a fantastic tool!
