### ISSUE TITLE
support: How to use with Arduino

### ISSUE THREAD

**Issue by dsfazgadfgr** [Tbruno25/can-explorer#17]
Hello and thank you for your posts on hacking the can bus.  My Arduino Nano and MCP2515 are functioning properly and collecting data.  I'd like to use can-explorer to help interpret that data but can't seem to find the proper settings for Interface and channel.  The Ibus on my Saab runs at 33.33kbps.  Thanks

**Comment by Tbruno25** [comment]
I would recommend utilizing the [mcp example](https://github.com/Tbruno25/can-explorer/blob/main/scripts/mcp_example.ino) to collect data. Make sure to modify the baudrate and clock speed accordingly. This will ensure the data is formatted in a compatible way.

From there there's 2 options:

1. View the data live by utilizing the `serial` interface in `can-explorer`. I have not tested this.

2. Record and save a log. Replay the log on a virtual interface using `canplayer` from the `can-utils` package while visualizing the data. This has been verified to work.

Hope this helps!

**Comment by Tbruno25** [comment]
closing for now but feel to re-open!
