### ISSUE TITLE
Gui under windows shows half button

### ISSUE THREAD

**Issue by designer2k2** [Tbruno25/can-explorer#19]
Hello,

thanks a lot for this usefull tool!

One small bug i have under windows 10 is that the gui is showing the Start/Stop and Clear buttons only half and i have a scrollbar:
![Animation](https://github.com/Tbruno25/can-explorer/assets/1591573/7ce7ba3b-24f2-4c3c-9c1f-09f0af8ab2e4)

I installed the can-explorer with pipx

**Comment by Tbruno25** [comment]
will definitely look into this. 

also -- thank you for taking the time record the issue, it helps a lot!

**Comment by Tbruno25** [comment]
This should be solved in `0.1.7` :rocket:

**Comment by designer2k2** [comment]
confirmed, 0.1.7 has fixed this, thanks!
