### ISSUE TITLE
support: is the network streaming from OVMS (GVRET) supported

### ISSUE THREAD

**Issue by ramack** [Tbruno25/can-explorer#22]
I recently bought a OVMS and wonder if it is possible to connect with can-explorer to the network port streaming CAN from the ODB2 in GVRET format.

**Comment by Tbruno25** [comment]
I am not familiar with OVMS. However, this tool should be able to visualize anything that `python-can` is able to connect to. I recommend browsing their docs to see if it satisfies your use case.
