### ISSUE TITLE
reading from file 

### ISSUE THREAD

**Issue by epe** [Tbruno25/can-explorer#23]
Hi, Is it possible to use a logfile earlier created with candump? 

I tried piping a cadump log to can-explorer in the terminal .. 

Is there a protocol like virtual that allows opening or would i need some tool like can-replay?

**Comment by Tbruno25** [comment]
I recommend using `canplayer` to replay the logs, it's part of the popular `can-utils` package. You can replay over vcan and then visualize using `can-explorer`. Hope this helps!
